version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://128.199.95.97:8000
      - NEXT_PUBLIC_APP_URL=https://aeoninvestmentstechnologies.com
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - ENVIRONMENT=development
      - CORS_ORIGINS=["http://localhost:3000","https://atom-defi.vercel.app"]
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://128.199.95.97:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add database for future use
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: atom_db
  #     POSTGRES_USER: atom_user
  #     POSTGRES_PASSWORD: atom_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
